#!/bin/bash

# usage thmake [r|d]

THREAD_NUM=10

if [ $# -eq 2 ]
then
    THREAD_NUM=$2
fi

if [ $# -eq 0 ]
then
    echo "release mode"
    make DEBUG=0 THREAD_NUM=$THREAD_NUM
elif [ $# != 0 ]
then
    if [ $1 == r ]
    then
	echo "release mode"
	make DEBUG=0 THREAD_NUM=$THREAD_NUM
    elif [ $1 == d ]
    then
	echo "debug mode"
	make DEBUG=1 THREAD_NUM=$THREAD_NUM
    else
	echo "wrong args"
	exit 1
    fi
else
    echo "wrong args num"
    exit 1
fi
     
